### ISSUE TITLE
Off-by-one error

### ISSUE THREAD

**Issue by bjhartin** [takezoe/scala-retry#1]
I think there is an error [here](https://github.com/takezoe/scala-retry/blob/ff751361bb8cd9e63d78ed77384968d76c98d186/src/main/scala/com/github/takezoe/retry/package.scala#L17):

```scala
  if(count == config.maxAttempts){
```

If I configure it for `maxAttempts  = n`, it will execute the function `n + 1` times.

Am I missing something?  :smile:

**Comment by takezoe** [comment]
Sorry for my very late reply. You are right. 😅 Fixed in 92c8d3230cc4507ec693829d27759cce25bd37a0.

**Comment by takezoe** [comment]
Ah, no. `maxAttempts` means the max retry attempts. For example, `maxAttempts = 1` means retry once. So, the current behaviour is intentional.
